/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import lo.*;

/**
 *
 * @author chenc
 */
public class BuscarProd extends javax.swing.JFrame
{
    Tools to = new Tools();

    Consultas cl = new Consultas();
    /**
     * Creates new form BuscarProd
     */
    public BuscarProd()
    {
        initComponents();
        setIconImage(to.icono());
        comboca();
        mosDa("","");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbCate = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpro = new javax.swing.JTable();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar producto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 220, -1));

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtBuscarKeyPressed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 250, 36));

        jLabel2.setBackground(new java.awt.Color(84, 194, 66));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Buscar");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 120, 36));

        cbCate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbCate.setPreferredSize(new java.awt.Dimension(43, 32));
        cbCate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbCateActionPerformed(evt);
            }
        });
        jPanel1.add(cbCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 300, -1));

        tbpro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbpro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(tbpro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 680, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbCateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbCateActionPerformed
    {//GEN-HEADEREND:event_cbCateActionPerformed
        String f= cbCate.getSelectedItem().toString();
        if (!f.equals("Seleciona una categoría"))
        {
            mosDa("",f);
        }
    }//GEN-LAST:event_cbCateActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel2MouseClicked
    {//GEN-HEADEREND:event_jLabel2MouseClicked
        String bus = txtBuscar.getText();
        if (bus.isEmpty())
        {
            to.error("No deje campos vacíos", "Error de campos");
        } else
        {
            mosDa(bus,"");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtBuscarKeyPressed
    {//GEN-HEADEREND:event_txtBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String bus = txtBuscar.getText();
            if (bus.isEmpty())
            {
                to.error("No deje campos vacíos", "Error de campos");
            } else
            {
                mosDa(bus, "");
            }
        }else if(evt.getKeyCode() == KeyEvent.VK_F5)
        {
            mosDa("","");
            cbCate.setSelectedItem("Seleciona una categoría");
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void comboca()
    {
        cbCate.addItem("Seleciona una categoría");
        ArrayList ca = cl.consuCate();
        for (int j = 0; j < ca.size(); j++)
        {
            String cat = ca.get(j).toString();
            cbCate.addItem(cat);
        }
    }
    public void mosDa(String clave, String cate)
    {
        DefaultTableModel mode = new DefaultTableModel();
        mode.addColumn("Clave");
        mode.addColumn("Nombre");
        mode.addColumn("Cantidad");
        mode.addColumn("Precio");
        mode.addColumn("Costo");
        tbpro.setModel(mode);
        to.colorTable(tbpro, 5);
        Consultas cl = new Consultas();
        cl.consuPro(mode, clave, cate);
        if (!txtBuscar.getText().isEmpty())
        {
            txtBuscar.setText("");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BuscarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BuscarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BuscarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BuscarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new BuscarProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbpro;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
